spring:
  application:
    name: acs-2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATASOURCE_HOST}:${DATASOURCE_PORT:3306}/${DATASOURCE_DB}
    username: ${DATASOURCE_USR}
    password: ${DATASOURCE_PWD}
  liquibase:
    change-log: classpath:/db.changelog/16-01-changelog.xml
  web:
    resources:
      add-mappings: false

acs:
  delimiter: ${ACS_DELIMITER:.}
  definitions:
    # Supports all types of input stream sources
    # Example: file://path
    source: ${ACS_DEFINITIONS_SOURCE}