spring:
  application:
    name: acs-2
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATASOURCE_HOST}:${DATASOURCE_PORT:3306}/${DATASOURCE_DB}
    username: ${DATASOURCE_USR}
    password: ${DATASOURCE_PWD}
  liquibase:
    change-log: classpath:/db.changelog/18-01-changelog.xml
  web:
    resources:
      add-mappings: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.orm.jdbc.bind: INFO

springdoc:
  swagger-ui:
    path: /api-spec.html

acs:
  delimiter: ${ACS_DELIMITER:.}
  definitions:
    # Supports all types of input stream sources
    # Example: file://path
    source: ${ACS_DEFINITIONS_SOURCE}
    format: ${ACS_DEFINITIONS_FORMAT:YAML}