spring:
  application:
    name: acs-plane
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
    mongodb:
        uri: mongodb://${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/acs-plane