name: JUnit Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    # Latest ubuntu runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup JDK 17 for running Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Run tests
      - name: Run all tests from root
        run: ./gradlew test

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'