name: JUnit Tests

on:
  push:
    branches:
      - '**'

jobs:
  test:
    # Latest ubuntu runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup JDK 17 for running Gradle
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # Run tests
      - name: Run all tests from root
        run: ./gradlew test

      - name: Upload test reports artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: '**/build/test-results/test/*.xml'

      - name: Test Reporter
        uses: dorny/test-reporter@v1
        with:
          name: Gradle Tests
          path: '**/build/test-results/test/*.xml'
          reporter: junit